"""Initial schema

Revision ID: 5ed0d9196d74
Revises: 
Create Date: 2026-03-31 14:46:09.947463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ed0d9196d74'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        # Add metadata_json with a default empty JSON for existing rows
        batch_op.add_column(
            sa.Column('metadata_json', sa.JSON(), nullable=False, server_default=sa.text("'{}'::json"))
        )
        # Add updated_at column with current timestamp for existing rows
        batch_op.add_column(
            sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.func.now())
        )

    # Remove server defaults if you don't want them for new rows
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.alter_column('metadata_json', server_default=None)
        batch_op.alter_column('updated_at', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('metadata_json')

    # ### end Alembic commands ###
